### ISSUE TITLE
workflow.core forces getenv = true for vanilla executables

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1270]
The line

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/core.py#L686

forces ``getenv = true`` for vanilla universe jobs that use installed executables. This breaks using bundles from ``/cvmfs`` on OSG. If the user is using the RHEL7 virtual environment to create the workflow, then this causes jobs to fail on RHEL6 sites with
```
python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
2016-11-20 19:58:16: Last command exited with 127
```

The workaround for now is to pass
```
'pegasus_profile-inspiral:pycbc|installed:False'
```
to the ``--config-overrides`` but this should be fixed properly. The best thing is probably to delete line 686 completely, and set this as a pegasus property in ``executables.ini``

**Comment by ahnitz** [comment]
Duncan, I don't think this is a bug, and really should be the default behavior. What in your environment is causing the problem?  Do you understand why exactly the bundle is failing here? 

@spxiwh  What do you think?

**Comment by duncan-brown** [comment]
@ahnitz it's not the bundle that is failing, it is the python program ``pegasus-transfer`` that is run before the bundle to stage in the data.

The problem is that ``getenv = True`` on an RHEL6 site forces the use of whatever python was used to plan the workflow (i.e. python2.7, if the workflow was planned on RHEL7). This then causes the ``pegasus-transfer`` executable to fail on the remote site, as the virtualenv's python2.7 is found before the system python2.6. Whether or not the ``getenv = True`` should be set should be decided on a per-executable basis, not forces for all vanilla jobs. 

The current code is too tied to an LDG environment that expects that the user is using dynamic python code on a shared filesystem. It would be better to move the default setting to a property in ``executables.ini`` set for all jobs (like the default RAM). Then it can be overridden as needed. The way it is set now by hard coding in workflow.core leaves no way to override the default.

**Comment by ahnitz** [comment]
@duncan-brown Ok, so let me know if the following is correct. You have a virtualenv on CVMS which includes a different version of python than on the OSG site. You environment causes this version to be picked up first before the system python, and because it is not really built for that environment (and doesn't include the required .so files like the bundle) any other python program will fail to run such as the pegasus-transfer exe. Is that right? In any case, I'm getting back to sleep, but thanks for explaining the issue. I'd like a backwards compatible solution to this, which I think is possible by moving the profile to the executable level, where it *can* be overridden.

**Comment by duncan-brown** [comment]
@ahnitz yes, that's right. Moving it up a level is the right thing to do.

**Comment by duncan-brown** [comment]
Closing this as it has been resolved by other changes.
