### ISSUE TITLE
Thinning Should be Per-Ensemble, not Per-Walker

### ISSUE THREAD

**Issue by farr** [ligo-cbc/pycbc#1815]
It is an error, and will lead to biased results, to thin the chains from the emcee samplers on a per-walker basis rather than a per-ensemble basis.  It will also give biased results from Kombine unless you run for a *very long time* (much longer than you need to).  The correct algorithm is to determine the ACL from the ensemble as a whole (by examining the time-series of the mean of the walkers coordinates over the ensemble), and then thin the entire ensemble by this much.  After that, you can compress the "walker" dimension and treat the set of samples collectively.

I'll work on a patch in my spare time, but if you get to it first go ahead.  This patch should also address #1807

**Comment by cmbiwer** [comment]
Yeah so right now the default is to compute the ACL for each walker, then find the maximum from that set of ACLs. And use the maximum ACL over the walkers for the entire ensemble.

When I added it, I chose what I thought was more conservative and it will require more iterations as you say. I'm done traveling/moving now. I'll see about getting to this and #1807.

**Comment by farr** [comment]
Hi Chris,

Great---I guess I missed the maximum statement.  I'm sorry for flagging it
as such an urgent bug, when it's just an inefficiency rather than a bias.
I'll see if I can contribute something that does a little better on a week
or two timescale; if you get to it first, go ahead.

will

**Comment by cdcapano** [comment]
@farr Somewhat related question about this: I just added a burn_in module to master. See #1797. Two of the possible functions in there, `max_posterior` and `posterior_step`, will estimate burn-in iterations on a per-walker basis. The first function checks when a walker first gets within `dim/2` of the max(log likelihood + log prior) over all of the walkers (`dim` = the number of variable parameters); the second checks when the last time the walker's log likelihood + log prior jumped by more than `dim/2`. These are two tests that, as I understood from Vivien, are used in lalinference.

I was also under the impression that in lalinference you gather independent samples on a per-walker basis; i.e., start at a different iteration for each walker, so that you potentially get a different number of samples from different walkers. I had assumed that you would also use the ACL for each walker in that case, but that's apparently not true. Is it also wrong to use a different start index for each walker? In other words, would it be bad to do this:`[walker_i[burn_in_i:end:acl] for i in nwalkers]`? If so, is this just a kombine-specific problem, or is this true of all MCMC samplers?

Right now we're using the maximum burn in iteration from all walkers for the start index, and as Chris said, the maximum ACL across all walkers for the interval. I was going to write a patch to allow collecting on a per-walker basis, but I obviously don't want to do that if it will bias results.

**Comment by farr** [comment]
@cdcapano If you use a different iteration per-walker for burnin on *ensemble* methods (Kombine, emcee, etc) then you will introduce bias, so you'll have do it the way you do now: choose a single burn-in index for all walkers, choose a single ACL for all walkers, etc.  The reason you are getting confused is that LALInference does not, by default, use an ensemble method; there is only *one* walker at each temperature.  We do use a per-temperature burn-in criterion to know when to exit the "burnin" phase of the code at each temperature, but don't start collecting samples for "the posterior" from the zero-temperature chains until all the temperatures are burned in.

**Comment by cdcapano** [comment]
@farr Ok, thanks for the explanation. I didn't realize LALInference did not use an ensemble method. You just saved me some work! I do have a few more questions about estimating burn in for multiple temperature chains, but I'll send you an email.

**Comment by cdcapano** [comment]
Fixed by #1832.
