### ISSUE TITLE
Executable to determine concident livetime

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#233]
One of the things we'll have to do fairly regularly in O1 (and beyond) is to wait for enough coincident livetime to be accumulated before cutting the next analysis block. Can we quickly put together a simple script to calculate this given a veto definer and the segment names, etc? 

Basic features
 * take gps start/end time
 * account for applying vetoes
 * account for minimum science segment length 

Bonus features 
 * Report the maximum FAR we can estimate from the available time (include number of background bins?)
 * handle more than two detectors (needed for beyond O1)

Please respond if you can put this together, or if there is already a good way to get this information.

**Comment by duncan-brown** [comment]
Ian says that the data checker can do this. I will look into it.

**Comment by spxiwh** [comment]
Looking closer, maybe the dayhopecheck example is a little closer to what we need, except it doesn't do the union of analysable times between the two ifos. Also note that a lot of the code in dayhopecheck ended up in the setup_analysislogging function, so that could be called directly.

Let me know if someone is taking this on and I can provide some more pointers.

**Comment by duncan-brown** [comment]
Resolved by pull request https://github.com/ligo-cbc/pycbc/pull/284
