### ISSUE TITLE
Incompatibility between different LIGOTimeGPS

### ISSUE THREAD

**Issue by titodalcanton** [ligo-cbc/pycbc#42]
I hit this error trying to analyze ER7 data. For some reason, a call to pycbc.events.veto.segments_to_file() is given a segment list made of segments with a variety of time types, even inside a single segment. It looks like this is the result of arithmetic operations between segment lists of different types. One of the segments happens to have a lal.LIGOTimeGPS type. This raises a ValueError when the time is casted to a glue.ligolw.lsctables.LIGOTimeGPS in segments_to_file() (apparently the cast is not allowed). I suppose the proper solution would be for the cast to succeed (fixing glue?). But maybe PyCBC can be more robust about such problems. What do people think? Can we just switch to using lal.LIGOTimeGPS everywhere?

**Comment by ahnitz** [comment]
We should use lal.LIGOTimeGPS everywhere and not the one from glue's lal.py. I suppose though if we cast first to float, then the cat from float to glue's LIGOTimeGPS will succeed? Not a great solution, but maybe good enough for now, unless someone has a better solution.

**Comment by titodalcanton** [comment]
I actually found that the glue writer just works if I use a lal.LIGOTimeGPS... So see request https://github.com/ligo-cbc/pycbc/pull/45

**Comment by tdent** [comment]
Hi Alex, all - 

could someone explain the relevant difference(s) between lal.LIGOTimeGPS and glue.lal.LIGOTimeGPS?  The glue code seems to have rather a lot of switches and type-dependent assignments in __init__ .. I don't know if the swiglal version has equivalent complications. 

Cheers, Tom

--
-----------------------------------------
Institute for Gravitational Physics
(Albert Einstein Institute)
Callinstr. 38 
D-30167 Hannover, Germany

**Comment by tdent** [comment]
Hi,

The thing in glue was written at a time when there was some sort of
policy that glue shouldn't require anything from lal in order to
function.  It was impossible to avoid having a LIGOTimeGPS-like object,
so a pure Python replacement got written.  Don't use it if you can avoid
it.  For as long as there has been the thing in glue there was a
pylal-supplied wrapping of the C type in LAL that could've been used
instead (and should've been).  Now there is the swig wrapping of the C
type provided by lal itself.  Glue's test suite compares the results of
arithmetic operations performed with the LAL and glue versions to each
other so there should be no concerns about the correctness of the thing
in glue, but it's very slow.

							-Kipp
