### ISSUE TITLE
The minifollowup sub-daxes need to have staging site set for OSG

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#646]
Pegasus does not propagate staging-site down into sub-workflows, so it must be set on a per workflow basis. Currently only the main.dax has the staging site set in the ini files. It also needs be set for the follow-up workflows.

**Comment by lppekows** [comment]
The errors in the workflow that seemed to be due to this turned out to have a different cause.  We will only need to pass staging information down to subdaxes if we want to run those subdaxes on remote sites.  As there are no plans to do that at present this issue could either be removed from the 1.3.2 milestone or closed.
