### ISSUE TITLE
kombine versoin on pyipi too old

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#930]
The version of kombine on pypi which is installed by pycbc is too old, requiring an install from source.

**Comment by cdcapano** [comment]
Here's what happens: if you install pycbc, then try to run pycbc_inference, you'll get the following error:

``
 File "/home/cdcapano/venvs/pycbc-master/local/lib/python2.7/site-packages/PyCBC-f85e99-py2.7.egg/pycbc/inference/sampler.py", line 101, in __init__
    transd=transd, processes=processes)
TypeError: __init__() got an unexpected keyword argument 'transd'
``

If you then re-install kombine from source (the most recent master), it'll work. Apparently the version of kombine that is on pypi does not have the transd argument in the sampler.

**Comment by cmbiwer** [comment]
I haven't been able to reproduce this.

So I login to atlas2:
```
virtualenv opt/kombine
source ~/opt/kombine/bin/activate
pip install numpy==1.9.3
pip install scipy==0.16.0
pip install kombine
```

Then open up ipython and the docstring shows:
```
Type:       type
String Form:<class 'kombine.sampler.Sampler'>
File:       /home/cbiwer/opt/kombine/lib/python2.7/site-packages/kombine/sampler.py
Docstring:
An Ensemble sampler.

The :attr:`chain` member of this object has the shape: `(nsteps, nwalkers, ndim)` where `nsteps`
is the stored number of steps taken thus far.

:param nwalkers:
    The number of individual MCMC chains to include in the ensemble.

:param ndim:
    Number of dimensions in the parameter space.  If `transd` is ``True`` this is the number of
    unique dimensions across the parameter spaces.

:param lnpostfn:
    A function that takes a vector in the parameter space as input and returns the natural
    logarithm of the posterior probability for that position.

:param transd:
    If ``True``, the sampler will operate across parameter spaces using a
    :class:`.clustered_kde.TransdimensionalKDE` proposal distribution. In this mode a masked
    array with samples in each of the possible sets of dimensions must be given for the initial
    ensemble distribution.

:param processes: (optional)
    The number of processes to use with :mod:`multiprocessing`.  If ``None``, all available
    cores are used.

:param pool: (optional)
    A pre-constructed pool with a map method. If ``None`` a pool will be created using
    :mod:`multiprocessing`.
Constructor information:
 Definition:kombine.Sampler(self, nwalkers, ndim, lnpostfn, transd=False, processes=None, pool=None, args=[])
```

I can see it in the module that was installed too.

The version of kombine installed was:
```
In [9]: kombine.__version__
Out[9]: '0.5.0'
```

Do you have a path to your virtualenv?

**Comment by cmbiwer** [comment]
I also tried building pycbc from the ``install_pycbc.sh`` script on sugar-dev3 to see what I'd get since I haven't build a new virtualenv in awhile. The script failed compiling ``lalapps_inspinj`` with:
```
collect2: ld returned 1 exit status
make: *** [lalapps_inspinj] Error 1
```

So how are you all building this?

**Comment by cmbiwer** [comment]
Soumi just told me that we can no longer build the O1 release (``lalsuite-v6.36``)... So I guess I'll try a newer release.

**Comment by duncan-brown** [comment]
@cmbiwer it's possible to use the install script to build the O1 branch if you comment out the lines that do the ``#Build a static lalapps_inspinj and install it`` 

It's on my list to fix this, but I haven't had chance.

**Comment by cmbiwer** [comment]
@duncan-brown Thanks for letting me know, I'll keep that in mind.

@cdcapano @ahnitz I just built pycbc with the install script in a new virtualenv and it installed kombine v0.5.0 just like pip, and I was able to run ``pycbc_inference``.

**Comment by cdcapano** [comment]
Ok, after digging into this some more, the problem appears to be that the version numbering history of kombine is a bit messed up. At some point in the past there was a version called "1.1" that is actually older than the current version, which is 0.6.4. See:
https://www.versioneye.com/python/kombine/0.6.4
Click on the "show all" button in the box on the right, and you'll see the version history. You can see that there's a version "1.1" that was added on June 2, 2015, whereas the current version, 0.6.4, was added on August 21, 2015.

Somehow (I'm not sure how) I got the 1.1 version installed in my virtual environment on atlas. As a result, when I run pycbc's setup.py, it sees that there is 1.1 egg available in my site-packages, which it thinks is newer than 0.6.4 because the number is larger. It then removes 0.6.4 from my path and switches to 1.1; here's the output of setup.py:
```
Installed /home/cdcapano/venvs/pycbc-master/lib/python2.7/site-packages/PyCBC-b2ecac-py2.7.egg
Processing dependencies for PyCBC===b2ecac
Searching for kombine==1.1
Best match: kombine 1.1
Processing kombine-1.1-py2.7.egg
Removing kombine 0.6.4 from easy-install.pth file
Adding kombine 1.1 to easy-install.pth file
```
I fixed this by running `pip uninstall kombine==1.1`, which removed the bad egg. Now when I run setup.py, I get:
```
Installed /home/cdcapano/venvs/pycbc-master/lib/python2.7/site-packages/PyCBC-b2ecac-py2.7.egg
Processing dependencies for PyCBC===b2ecac
Searching for kombine==0.6.4
Best match: kombine 0.6.4
Processing kombine-0.6.4-py2.7.egg
Adding kombine 0.6.4 to easy-install.pth file
```
So that fixed the problem for me. I'm not sure if there's anything we can do about this on our end, other than telling people to look out for version 1.1. @ahnitz @duncan-brown any suggestions?

In any event, I'm going to close #931, since that's not the appropriate fix for this. I would say that we should add a minimum version number requirement to kombine, but that would not have fixed this problem.

**Comment by cdcapano** [comment]
I figured out how I get kombine 1.1. If you have no kombine installed prior to running `pycbc's setupy.py`, then it ends up downloading 1.1 from pypi. I found this by uninstalling kombine from my virtual environment:
```
(pycbc-master)[cdcapano@atlas9 pycbc]$ pip uninstall kombine
Uninstalling kombine-0.6.4:
  /home/cdcapano/venvs/pycbc-master/lib/python2.7/site-packages/kombine-0.6.4-py2.7.egg
Proceed (y/n)? y
  Successfully uninstalled kombine-0.6.4
```
Then re-installing pycbc, I see in the output:
```
Installed /home/cdcapano/venvs/pycbc-master/lib/python2.7/site-packages/PyCBC-b2ecac-py2.7.egg
Processing dependencies for PyCBC===b2ecac
Searching for kombine
Reading https://pypi.python.org/simple/kombine/
Best match: kombine 1.1
Downloading https://pypi.python.org/packages/b7/db/f2f88456004788a2f8024d7634f5ebac5e1f54b47a33d1bbd4ea89cda525/kombine-1.1-py2.7.egg#md5=5c46970a6c8fcf17d5eeb8b1fa85743a
Processing kombine-1.1-py2.7.egg
Moving kombine-1.1-py2.7.egg to /home/cdcapano/venvs/pycbc-master/lib/python2.7/site-packages
Adding kombine 1.1 to easy-install.pth file
```
So anyone doing a fresh install of pycbc without a prior install of kombine is going to run into this. @ahnitz @duncan-brown  Is there some way to prevent setup.py from installing 1.1? (And also 1.0, since that was also added prior to the current version.)

**Comment by ahnitz** [comment]
Ben has updated the version in PyPI, closing.
