### ISSUE TITLE
InferenceFile.read_samples_from_walkers without walkers option has unknown organization

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#948]
So I don't really understand the output of ``InferenceFile.read_samples_from_walkers`` when ``walkers=None``. And this is used by ``InferenceFile.read_samples``.

So before ``InferenceFile.read_samples_from_walker`` returned a ``numpy.array`` with shape (niterations,), modulo any thinning options.

Before #940 ``InferenceFile.read_samples`` returned a (nwalkers,niterations) array. I had a branch to have ``read_samples`` return a (niteration,nwalker,ndim) array (ie. returns samples for many parameters). But since #940 rewrote a lot of those functions I didn't make a PR.

Now ``InferenceFile.read_samples_from_walkers`` returns a ``WaveformArray``.

But the following lines:
```
            past_samples = fp.read_samples_from_walkers(variable_args,
                                              thin_start=0, thin_interval=1)
            print past_samples.shape
            print fp.niterations
            print fp.nwalkers
```

Produce the output:
```
(500,)
50
10
```

So the output has shape (500,)? Its not immediately clear to me how this is this organized.

500 is the size of all the samples so its obviously wrong to just take this output. And each element seems to be an iterable of all the parameters at that point.

So mainly what I want to ask: How do I get all the samples from a specific walker from this output? Is it possible?

Maybe its because I'm just not familiar with ``WaveformArray`` but I don't get how this is supposed to be organized. The function seems fine as long as you supply a number for the walker.

This is more of a comment but: I also can't index it like a ``numpy.array`` even though the elements are iterables, eg. ``samples[0,0]`` doesn't work. I think there's some elegance to having a ``numpy.array`` with shape (niterations,nwalkers,ndim) or (niterations,nwalkers) or (niterations,).

**Comment by cdcapano** [comment]
Hi Chris,

Yes, the output array has shape (500,). In a record array (which is what `WaveformArray` inherits from, via `FieldArray`), parameters are not stored as extra dimensions, but as a 1 dimensional array in which each element has multiple fields. The equivalent in C would be a linked list of structures.

So, in the case you gave above, `past_samples` has a field for each variable arg. Say the variable args are `mass1`, `mass2`, and `tc`. To get one of these fields, you simply index the array using the name of the field, rather than a number. So, if you wanted mass1, you would do `past_samples['mass1']`. This would return a one-dimensional numpy array of floats. If you wanted the ith mass1, it's `past_samples['mass1'][i]` or `past_samples[i]['mass1']`. Alternatively, you can access fields as though they were attributes; i.e., `past_samples.mass1` will also return a 1d array of floats, while the ith element can be obtained via `past_samples[i].mass1` or `past_samples.mass1[i]`.

This way of indexing fields by names rather than indices of an extra dimension has a few advantages. First, you don't need to keep track of which column index corresponds to which field. Writing `past_samples.mass1` is clearer than `past_samples[:,0]`. Second, with WaveformArray you can use functions of fields as indices; e.g., you can get an array of the symmetric mass ratios with `past_samples['mass1*mass2/(mass1+mass2)**2']`. Also, methods defined under WaveformArray look like fields; e.g.,  you can also get the symmetric mass ratio with `past_samples['eta']` since eta is one of the methods defined in `WaveformArray`. This is why the `parameters` option is so flexible; you can just pass the string from the command line directly to the array as an index to retrieve the desired functions.

All of that said, if you want/need the parameters as a 2D array, it's fairly straight foward to convert. This is done, for instance, in `plot_posterior`:
```
x = numpy.zeros((samples.size, len(parameters)))
for ii,p in enumerate(parameters):
    x[:,ii] = samples[p]
```
If you like I can add such conversion as a method on FieldArray, so you can just call this as a function.

Right now `read_samples_from_walkers` will concatenate the thinned results from all of the desired walkers into a single 1D WaveformArray. If you do not provide any walkers, it will get the thinned results from all of the walkers. That's why with 50 walkers with 10 samples each, you got an array with shape (500,). If you set `walkers=0`, you'd get a 1D array with 10 samples; `walkers=[0,1]` would give you a 1D array with 20 samples, etc.

If you really want each walker to be another dimension, it is possible to create multi-dimensional WaveformArrays. For example `arr = WaveformArray((10,50), names=['mass1', 'mass2'])` would give you a WaveformArray with shape (10,50). This still has fields mass1 and mass2, just that now when you retrieve a field you'll get a 2D array of floats rather than a 1D; e.g., `arr.mass1` would return an array of floats with shape (10,50). If you like, we could make it so that if `read_samples_from_walkers` is provided a list of walkers it will return a 2D WaveformArray, with the second index giving the walker. Higher dimensional record arrays can be a bit confusing though, so I'd hesitate doing this.

Does that explain it?

**Comment by cmbiwer** [comment]
Hey Collin thanks for the explaination on that.

I guess it just means if we want to get the walkers' samples we will write the loop https://github.com/ligo-cbc/pycbc/blob/master/bin/inference/pycbc_inference_plot_samples#L69 instead of something like ``past_samples[:,i,j]``. Its probably simpler than working with the 2-D array.

I guess I don't see the reason for the ``InferenceFile.read_samples`` function anymore then. Perhaps we just rename ``InferenceFile.read_samples_from_walkers`` -> ``InferenceFile.read_samples``? Do you think this is appropriate?

**Comment by cdcapano** [comment]
Yeah, I think that's a good idea. Do you want to submit a patch to do that?

**Comment by cmbiwer** [comment]
Hey Collin, sure I'll make a PR. After I submit the PR, I'll close this issue.

**Comment by cmbiwer** [comment]
#954 renames ``InferenceFile.read_samples_from_walkers``.
